
package wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebFault(name = "JPlagException", targetNamespace = "http://www.ipd.uni-karlsruhe.de/jplag/types")
public class JplagException
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private JPlagException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public JplagException(String message, JPlagException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public JplagException(String message, JPlagException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: wsdl.JPlagException
     */
    public JPlagException getFaultInfo() {
        return faultInfo;
    }

}
