/*
 * University of Illinois/NCSA
 * Open Source License
 *
 * Copyright (c) 2012 University of Illinois at Urbana-Champaign.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal with the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimers.
 *
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimers in the documentation and/or other materials provided
 *       with the distribution.
 *
 *     * Neither the names of the CoMoTo Project team, the University of
 *       Illinois at Urbana-Champaign, nor the names of its contributors
 *       may be used to endorse or promote products derived from this
 *       Software without specific prior written permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.illinois.cs.comoto.jplag.wsdl;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.encoding.literal.LiteralObjectSerializerBase;
import com.sun.xml.rpc.streaming.XMLReader;
import com.sun.xml.rpc.streaming.XMLReaderUtil;
import com.sun.xml.rpc.streaming.XMLWriter;
import com.sun.xml.rpc.wsdl.document.schema.SchemaConstants;

import javax.xml.namespace.QName;
import java.util.ArrayList;

public class ServerInfo_LiteralSerializer extends LiteralObjectSerializerBase implements Initializable {
    private static final javax.xml.namespace.QName ns1_userInfo_QNAME = new QName("", "userInfo");
    private static final javax.xml.namespace.QName ns3_UserInfo_TYPE_QNAME = new QName("http://jplag.ipd.kit.edu/JPlagService/types", "UserInfo");
    private CombinedSerializer ns3_myUserInfo_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_languageInfos_QNAME = new QName("", "languageInfos");
    private static final javax.xml.namespace.QName ns3_LanguageInfo_TYPE_QNAME = new QName("http://jplag.ipd.kit.edu/JPlagService/types", "LanguageInfo");
    private CombinedSerializer ns3_myLanguageInfo_LiteralSerializer;
    private static final javax.xml.namespace.QName ns1_countryLanguages_QNAME = new QName("", "countryLanguages");
    private static final javax.xml.namespace.QName ns2_string_TYPE_QNAME = SchemaConstants.QNAME_TYPE_STRING;
    private CombinedSerializer ns2_myns2_string__java_lang_String_String_Serializer;
    private static final javax.xml.namespace.QName ns1_submissions_QNAME = new QName("", "submissions");
    private static final javax.xml.namespace.QName ns3_Submission_TYPE_QNAME = new QName("http://jplag.ipd.kit.edu/JPlagService/types", "Submission");
    private CombinedSerializer ns3_mySubmission_LiteralSerializer;

    public ServerInfo_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle) {
        this(type, encodingStyle, false);
    }

    public ServerInfo_LiteralSerializer(javax.xml.namespace.QName type, java.lang.String encodingStyle, boolean encodeType) {
        super(type, true, encodingStyle, encodeType);
    }

    public void initialize(InternalTypeMappingRegistry registry) throws Exception {
        ns3_myUserInfo_LiteralSerializer = (CombinedSerializer) registry.getSerializer("", edu.illinois.cs.comoto.jplag.wsdl.UserInfo.class, ns3_UserInfo_TYPE_QNAME);
        ns3_myLanguageInfo_LiteralSerializer = (CombinedSerializer) registry.getSerializer("", edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo.class, ns3_LanguageInfo_TYPE_QNAME);
        ns2_myns2_string__java_lang_String_String_Serializer = (CombinedSerializer) registry.getSerializer("", java.lang.String.class, ns2_string_TYPE_QNAME);
        ns3_mySubmission_LiteralSerializer = (CombinedSerializer) registry.getSerializer("", edu.illinois.cs.comoto.jplag.wsdl.Submission.class, ns3_Submission_TYPE_QNAME);
    }

    public java.lang.Object doDeserialize(XMLReader reader,
                                          SOAPDeserializationContext context) throws java.lang.Exception {
        edu.illinois.cs.comoto.jplag.wsdl.ServerInfo instance = new edu.illinois.cs.comoto.jplag.wsdl.ServerInfo();
        java.lang.Object member = null;
        javax.xml.namespace.QName elementName;
        java.util.List values;
        java.lang.Object value;

        reader.nextElementContent();
        elementName = reader.getName();
        if (reader.getState() == XMLReader.START) {
            if (elementName.equals(ns1_userInfo_QNAME)) {
                member = ns3_myUserInfo_LiteralSerializer.deserialize(ns1_userInfo_QNAME, reader, context);
                if (member == null) {
                    throw new DeserializationException("literal.unexpectedNull");
                }
                instance.setUserInfo((edu.illinois.cs.comoto.jplag.wsdl.UserInfo) member);
                reader.nextElementContent();
            } else {
                throw new DeserializationException("literal.unexpectedElementName", new Object[]{ns1_userInfo_QNAME, reader.getName()});
            }
        } else {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_languageInfos_QNAME))) {
            values = new ArrayList();
            for (; ; ) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_languageInfos_QNAME))) {
                    value = ns3_myLanguageInfo_LiteralSerializer.deserialize(ns1_languageInfos_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo[values.size()];
            member = values.toArray((Object[]) member);
            instance.setLanguageInfos((edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo[]) member);
        } else if (!(reader.getState() == XMLReader.END)) {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_countryLanguages_QNAME))) {
            values = new ArrayList();
            for (; ; ) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_countryLanguages_QNAME))) {
                    value = ns2_myns2_string__java_lang_String_String_Serializer.deserialize(ns1_countryLanguages_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new java.lang.String[values.size()];
            member = values.toArray((Object[]) member);
            instance.setCountryLanguages((java.lang.String[]) member);
        } else if (!(reader.getState() == XMLReader.END)) {
            throw new DeserializationException("literal.expectedElementName", reader.getName().toString());
        }
        elementName = reader.getName();
        if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_submissions_QNAME))) {
            values = new ArrayList();
            for (; ; ) {
                elementName = reader.getName();
                if ((reader.getState() == XMLReader.START) && (elementName.equals(ns1_submissions_QNAME))) {
                    value = ns3_mySubmission_LiteralSerializer.deserialize(ns1_submissions_QNAME, reader, context);
                    if (value == null) {
                        throw new DeserializationException("literal.unexpectedNull");
                    }
                    values.add(value);
                    reader.nextElementContent();
                } else {
                    break;
                }
            }
            member = new edu.illinois.cs.comoto.jplag.wsdl.Submission[values.size()];
            member = values.toArray((Object[]) member);
            instance.setSubmissions((edu.illinois.cs.comoto.jplag.wsdl.Submission[]) member);
        } else {
            instance.setSubmissions(new edu.illinois.cs.comoto.jplag.wsdl.Submission[0]);
        }

        XMLReaderUtil.verifyReaderState(reader, XMLReader.END);
        return (java.lang.Object) instance;
    }

    public void doSerializeAttributes(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        edu.illinois.cs.comoto.jplag.wsdl.ServerInfo instance = (edu.illinois.cs.comoto.jplag.wsdl.ServerInfo) obj;

    }

    public void doSerialize(java.lang.Object obj, XMLWriter writer, SOAPSerializationContext context) throws java.lang.Exception {
        edu.illinois.cs.comoto.jplag.wsdl.ServerInfo instance = (edu.illinois.cs.comoto.jplag.wsdl.ServerInfo) obj;

        if (instance.getUserInfo() == null) {
            throw new SerializationException("literal.unexpectedNull");
        }
        ns3_myUserInfo_LiteralSerializer.serialize(instance.getUserInfo(), ns1_userInfo_QNAME, null, writer, context);
        if (instance.getLanguageInfos() != null) {
            for (int i = 0; i < instance.getLanguageInfos().length; ++i) {
                ns3_myLanguageInfo_LiteralSerializer.serialize(instance.getLanguageInfos()[i], ns1_languageInfos_QNAME, null, writer, context);
            }
        }
        if (instance.getCountryLanguages() != null) {
            for (int i = 0; i < instance.getCountryLanguages().length; ++i) {
                ns2_myns2_string__java_lang_String_String_Serializer.serialize(instance.getCountryLanguages()[i], ns1_countryLanguages_QNAME, null, writer, context);
            }
        }
        if (instance.getSubmissions() != null) {
            for (int i = 0; i < instance.getSubmissions().length; ++i) {
                ns3_mySubmission_LiteralSerializer.serialize(instance.getSubmissions()[i], ns1_submissions_QNAME, null, writer, context);
            }
        }
    }
}
