
package jplag;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.1-02/02/2007 03:56 AM(vivekp)-FCS
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JPlagService", targetNamespace = "http://www.ipd.uni-karlsruhe.de/jplag", wsdlLocation = "https://www.ipd.uni-karlsruhe.de/jplag/JPlagService.wsdl")
public class JPlagService
    extends Service
{

    private final static URL JPLAGSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("https://www.ipd.uni-karlsruhe.de/jplag/JPlagService.wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        JPLAGSERVICE_WSDL_LOCATION = url;
    }

    public JPlagService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JPlagService() {
        super(JPLAGSERVICE_WSDL_LOCATION, new QName("http://www.ipd.uni-karlsruhe.de/jplag", "JPlagService"));
    }

    /**
     * 
     * @return
     *     returns JPlagTyp
     */
    @WebEndpoint(name = "JPlagServicePort")
    public JPlagTyp getJPlagServicePort() {
        return (JPlagTyp)super.getPort(new QName("http://www.ipd.uni-karlsruhe.de/jplag", "JPlagServicePort"), JPlagTyp.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns JPlagTyp
     */
    @WebEndpoint(name = "JPlagServicePort")
    public JPlagTyp getJPlagServicePort(WebServiceFeature... features) {
        return (JPlagTyp)super.getPort(new QName("http://www.ipd.uni-karlsruhe.de/jplag", "JPlagServicePort"), JPlagTyp.class, features);
    }

}
