/*
 * University of Illinois/NCSA
 * Open Source License
 *
 * Copyright (c) 2012 University of Illinois at Urbana-Champaign.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal with the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimers.
 *
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimers in the documentation and/or other materials provided
 *       with the distribution.
 *
 *     * Neither the names of the CoMoTo Project team, the University of
 *       Illinois at Urbana-Champaign, nor the names of its contributors
 *       may be used to endorse or promote products derived from this
 *       Software without specific prior written permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.illinois.cs.comoto.jplag.wsdl;


public class FinishRequestData {
    protected java.lang.String oldUsername;
    protected java.lang.String username;
    protected java.lang.String password;
    protected java.util.Calendar expires;
    protected java.lang.String realName;
    protected java.lang.String email;
    protected java.lang.String emailSecond;
    protected java.lang.String homepage;
    protected java.lang.String reason;
    protected java.lang.String notes;
    protected java.lang.Integer state;
    protected java.lang.String mailSubject;
    protected java.lang.String mailMessage;

    public FinishRequestData() {
    }

    public FinishRequestData(java.lang.String oldUsername, java.lang.String username, java.lang.String password, java.util.Calendar expires, java.lang.String realName, java.lang.String email, java.lang.String emailSecond, java.lang.String homepage, java.lang.String reason, java.lang.String notes, java.lang.Integer state, java.lang.String mailSubject, java.lang.String mailMessage) {
        this.oldUsername = oldUsername;
        this.username = username;
        this.password = password;
        this.expires = expires;
        this.realName = realName;
        this.email = email;
        this.emailSecond = emailSecond;
        this.homepage = homepage;
        this.reason = reason;
        this.notes = notes;
        this.state = state;
        this.mailSubject = mailSubject;
        this.mailMessage = mailMessage;
    }

    public java.lang.String getOldUsername() {
        return oldUsername;
    }

    public void setOldUsername(java.lang.String oldUsername) {
        this.oldUsername = oldUsername;
    }

    public java.lang.String getUsername() {
        return username;
    }

    public void setUsername(java.lang.String username) {
        this.username = username;
    }

    public java.lang.String getPassword() {
        return password;
    }

    public void setPassword(java.lang.String password) {
        this.password = password;
    }

    public java.util.Calendar getExpires() {
        return expires;
    }

    public void setExpires(java.util.Calendar expires) {
        this.expires = expires;
    }

    public java.lang.String getRealName() {
        return realName;
    }

    public void setRealName(java.lang.String realName) {
        this.realName = realName;
    }

    public java.lang.String getEmail() {
        return email;
    }

    public void setEmail(java.lang.String email) {
        this.email = email;
    }

    public java.lang.String getEmailSecond() {
        return emailSecond;
    }

    public void setEmailSecond(java.lang.String emailSecond) {
        this.emailSecond = emailSecond;
    }

    public java.lang.String getHomepage() {
        return homepage;
    }

    public void setHomepage(java.lang.String homepage) {
        this.homepage = homepage;
    }

    public java.lang.String getReason() {
        return reason;
    }

    public void setReason(java.lang.String reason) {
        this.reason = reason;
    }

    public java.lang.String getNotes() {
        return notes;
    }

    public void setNotes(java.lang.String notes) {
        this.notes = notes;
    }

    public java.lang.Integer getState() {
        return state;
    }

    public void setState(java.lang.Integer state) {
        this.state = state;
    }

    public java.lang.String getMailSubject() {
        return mailSubject;
    }

    public void setMailSubject(java.lang.String mailSubject) {
        this.mailSubject = mailSubject;
    }

    public java.lang.String getMailMessage() {
        return mailMessage;
    }

    public void setMailMessage(java.lang.String mailMessage) {
        this.mailMessage = mailMessage;
    }
}
