/*
 * University of Illinois/NCSA
 * Open Source License
 *
 * Copyright (c) 2012 University of Illinois at Urbana-Champaign.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal with the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 *     * Redistributions of source code must retain the above copyright
 *       notice, this list of conditions and the following disclaimers.
 *
 *     * Redistributions in binary form must reproduce the above
 *       copyright notice, this list of conditions and the following
 *       disclaimers in the documentation and/or other materials provided
 *       with the distribution.
 *
 *     * Neither the names of the CoMoTo Project team, the University of
 *       Illinois at Urbana-Champaign, nor the names of its contributors
 *       may be used to endorse or promote products derived from this
 *       Software without specific prior written permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.illinois.cs.comoto.jplag.wsdl;


public class ServerInfo {
    protected edu.illinois.cs.comoto.jplag.wsdl.UserInfo userInfo;
    protected edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo[] languageInfos;
    protected java.lang.String[] countryLanguages;
    protected edu.illinois.cs.comoto.jplag.wsdl.Submission[] submissions;

    public ServerInfo() {
    }

    public ServerInfo(edu.illinois.cs.comoto.jplag.wsdl.UserInfo userInfo, edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo[] languageInfos, java.lang.String[] countryLanguages, edu.illinois.cs.comoto.jplag.wsdl.Submission[] submissions) {
        this.userInfo = userInfo;
        this.languageInfos = languageInfos;
        this.countryLanguages = countryLanguages;
        this.submissions = submissions;
    }

    public edu.illinois.cs.comoto.jplag.wsdl.UserInfo getUserInfo() {
        return userInfo;
    }

    public void setUserInfo(edu.illinois.cs.comoto.jplag.wsdl.UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    public edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo[] getLanguageInfos() {
        return languageInfos;
    }

    public void setLanguageInfos(edu.illinois.cs.comoto.jplag.wsdl.LanguageInfo[] languageInfos) {
        this.languageInfos = languageInfos;
    }

    public java.lang.String[] getCountryLanguages() {
        return countryLanguages;
    }

    public void setCountryLanguages(java.lang.String[] countryLanguages) {
        this.countryLanguages = countryLanguages;
    }

    public edu.illinois.cs.comoto.jplag.wsdl.Submission[] getSubmissions() {
        return submissions;
    }

    public void setSubmissions(edu.illinois.cs.comoto.jplag.wsdl.Submission[] submissions) {
        this.submissions = submissions;
    }
}
