/*
 * University of Illinois/NCSA
 * Open Source License
 *
 * Copyright (c) 2011 University of Illinois at Urbana-Champaign.
 * All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining
 * a copy of this software and associated documentation files (the
 * "Software"), to deal with the Software without restriction, including
 * without limitation the rights to use, copy, modify, merge, publish,
 * distribute, sublicense, and/or sell copies of the Software, and to
 * permit persons to whom the Software is furnished to do so, subject to
 * the following conditions:
 *
 *  Redistributions of source code must retain the above copyright
 * notice, this list of conditions and the following disclaimers.
 *
 *  Redistributions in binary form must reproduce the above
 * copyright notice, this list of conditions and the following
 * disclaimers in the documentation and/or other materials provided
 * with the distribution.
 *
 *  Neither the names of the CoMoTo Project team, the University of
 * Illinois at Urbana-Champaign, nor the names of its contributors
 * may be used to endorse or promote products derived from this
 * Software without specific prior written permission.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE CONTRIBUTORS OR COPYRIGHT HOLDERS BE LIABLE FOR
 * ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
 * WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS WITH THE SOFTWARE.
 */

// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package edu.illinois.cs.comoto.jplag.wsdl;


public class UpdateUserInfoParams {
    protected java.lang.String newPassword;
    protected java.lang.String newEmailSecond;
    protected java.lang.String newHomepage;

    public UpdateUserInfoParams() {
    }

    public UpdateUserInfoParams(java.lang.String newPassword, java.lang.String newEmailSecond, java.lang.String newHomepage) {
        this.newPassword = newPassword;
        this.newEmailSecond = newEmailSecond;
        this.newHomepage = newHomepage;
    }

    public java.lang.String getNewPassword() {
        return newPassword;
    }

    public void setNewPassword(java.lang.String newPassword) {
        this.newPassword = newPassword;
    }

    public java.lang.String getNewEmailSecond() {
        return newEmailSecond;
    }

    public void setNewEmailSecond(java.lang.String newEmailSecond) {
        this.newEmailSecond = newEmailSecond;
    }

    public java.lang.String getNewHomepage() {
        return newHomepage;
    }

    public void setNewHomepage(java.lang.String newHomepage) {
        this.newHomepage = newHomepage;
    }
}
